### ISSUE TITLE
CSS3新增功能整理一__关系选择器和伪类选择器

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#2]
### CSS3新增关系选择器和伪类选择器
- 关系选择器：

``` css
p~span{color:red;}/*p后的所有span字体颜色变红*/
```

新增的兄弟选择器，**只能选择标签之后的兄弟而不能选择之前的**
- 伪类选择器：

``` css
li:first-child{}/*选择li父元素的第一个li元素*/
li:last-child{}/*选择li父元素的最后一个li元素*/
li:nth-child(2){}/*选择li父元素的自定义个li元素*/
li:nth-child(even){}
li:nth-child(2n+1){}
li:nth-last-child(n){}/*同上，从最后一个子元素开始计数*/
li:only-child{}/*只有唯一一个子元素时可选择*/
```

新增的伪类选择器，虽说是"child"，但更像是同级选择器，**选择的都是属于父元素的指定子元素**

``` css
li:first-of-type{}/*选择li父元素的第一个li元素并且无视其他元素*/
/*其他类似child系列*/
```

新增的伪类选择器，类似上面的child系列，但区别在于**child系列无法过滤不同元素，而of-type系列可以**

``` css
.div1 p:first-child{color:red}
.div2 p:first-of-type{color:red}
```

``` html
<div class="div1">
<h1>1</h1> 
<p>2</p> <!--不会变色-->
<p>3</p> 
</div>
<div class="div2">
<h1>1</h1> 
<p>2</p> <!--变红-->
<p>3</p> 
</div>
```

以上为举例，证明of-type系列是会过滤掉非指定元素，而从指定元素开始计数

``` css
p:empty{}
```

选择所有没有子元素的p元素

``` css
html:root{}
```

选择文档根元素，并没有什么卵用
