### ISSUE TITLE
CSS3新增功能整理二__状态选择器、属性选择器和伪元素选择器

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#3]
### CSS3新增状态选择器、属性选择器和伪元素选择器
- 状态选择器：

``` css
input:enabled{color:red;}/*有enabled状态的input字体变红，input默认状态enabled*/
input:disabled{color:red;}/*选择disabled状态的input*/
input:checked{color:red;}/*选择checked状态的input，radio和checkbox*/
```

新增的状态选择器，选择指定状态的input
- 属性选择器：

``` css
li[id^="val"]{}/*选择属性（id）开头是val的li元素*/
li[id$="val"]{}/*选择属性（id）结尾是val的li元素*/
li[id*="val"]{}/*选择属性（id）含有val的li元素*/
/*css2属性选择器复习*/
li[id]{}
li[id="val"]{}
li[id~="val"]{}/*选择有val的li，无视空格*/
li[id|="val"]{}/*选择有val的li，无视-*/
```

新增的属性选择器，类似jquery的属性选择器
- 伪元素选择器

``` css
p::first-letter{}
p::first-line{}
p::after{content:"我是结尾"}/*after和before需要配合content使用*/
p::before{content:"我是开头"}
```

css3中的伪元素选择器为了和伪类选择器区分，将所有伪元素的":"改成了"::"，以上选择器与css2用法相同

``` css
p::selection{}/*选择所有被用户选取的p元素*/
```

新增的伪元素选择器，选择被用户选取的元素部分
