### ISSUE TITLE
CSS3新增功能整理三__文本属性

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#4]
### CSS3新增文本属性
- css1&2中的文本属性复习

``` css
p{
text-indent:10px;/*文本缩进*/
letter-spacing:5px;/*文字间隔*/
word-spacing:30px;/*单词间空格数*/
vertical-align:top;/*对齐方式*/
white-space:nowrap;/*空白符处理方式，用于强制不换行等功能*/
line-height:10px;/*行高*/
direction:rtl;/*文本流方向，从右往左看的语言使用*/
unicode-bidi:embed;/*同direction一同使用*/
}
```
- css3新增文本属性

1.text-overflow

``` css
p{
width:100px;
overflow:hidden;
white-space:nowrap;/*强制不换行*/
text-overflow:ellipsis;/*超出部分用...表示*/
}
```

text-overflow用于设置超出部分的文本表现方式，clip值：只修剪文本

2.text-align新增值

text-align新增了start和end两个值
start:内容对齐开始边界
end:内容对齐结束边界
css1老值为：left、right、center、justify(只有火狐可用)

3.text-decoration
新增了3个新的文本装饰线属性：
text-decoration-line：文本装饰线种类
text-decoration-color：文本装饰线颜色
text-decoration-style：文本装饰线样式
**三个新属性现在并不支持，只能使用原有属性的文本装饰线定义(overline...)**

4.text-shadow

``` css
h1{
font-size:30px;
text-shadow:5px 5px 5px red;
}
```

新增的文本阴影属性
第一个是水平平移值（可为负），第二个是垂直平移值（可为负），第三个是模糊程度（不可为负），第四个阴影颜色，**可设置多阴影，在一列阴影值后加逗号隔开**

5.text-fill-color和text-stroke(text-stroke-color,text-stroke-width)

text-fill-color为文字填充颜色，text-stroke为文字描边属性，2个属性配合可写出艺术字
**现在使用需加前缀**

6.tab-size

tab缩进值长度，默认为8
**只有在pre标签内才有效，html自动忽略空白符，使用需加前缀**

7.word-wrap

normal:默认值，允许内容顶开或溢出边界
bread-word:在边界换行，单词内部允许断行
**溢出文本处理（英文单词）**
