### ISSUE TITLE
CSS3新增功能整理四__边框属性

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#5]
### CSS3新增边框属性
- border-radius 圆角边框

``` css
.box{
border:2px solid #000;
border-radius:10px 5px 10px 3px;/*左上10px 右上5px 右下10px 左下3px*/
border-radius:50%;/*圆角为宽高50%的像素，变成椭圆或者正圆*/
border-radius:10px/15px;/*横轴半径10px 纵轴半径15px*/
}
```
- border-image 边框图片

``` css
.box{
border-image-source:url(...);/*边框的图片的路径*/
border-image-slice:30;/*边框向内偏移*/
border-image-width:30px;/*边框的宽度*/
border-image-outset:30px;/*边框图像区域超出边框的量*/
border-image-repeat:round;/*图像边框是否应平铺(repeated)、铺满(rounded)或拉伸(stretched)。stretched为默认属性*/
border-image:url(...) 30 30 round;/*简写*/
}
```
- box-shadow 边框阴影

``` css
.box{
box-shadow:10px 10px 5px 8px #000;/*横轴偏移10px 纵轴偏移10px 模糊距离5px 阴影尺寸8px 黑色*/
box-shadow:inset 10px 10px 5px #000;/*内阴影*/
}
```

Internet Explorer 不支持 border-image。
Internet Explorer 9+ 支持 border-radius 和 box-shadow 属性。
Firefox、Chrome 以及 Safari 支持所有新的边框属性。
注释：对于 border-image，Safari 5 以及更老的版本需要前缀 -webkit-。
Opera 支持 border-radius 和 box-shadow 属性，但是对于 border-image 需要前缀 -o-。
兼容性转自w3school
