### ISSUE TITLE
CSS3新增功能整理五__不透明度

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#6]
### CSS3不透明度设置

``` css
.box{
opacity:0.45;/*0.45的不透明度，1为不透明，0为100%透明*/
}
```

所有浏览器都支持 opacity 属性。
注释：IE8 以及更早的版本支持替代的 filter 属性。例如：**filter:Alpha(opacity=50)**。

opacity属性有继承性
