### ISSUE TITLE
CSS3新增功能整理六__背景属性

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#7]
### CSS3新增背景属性
- background-size 背景尺寸

``` css
.box{
background-size:100px 50px;/*设置背景尺寸固定宽高*/
background-size:50% 80%;/*使用百分比设置背景尺寸*/
background-size:cover;/*使背景图像完全覆盖背景区域。背景图像的某些部分也许无法显示在背景定位区域中*/
background-size:contain;/*把图像图像扩展至最大尺寸，以使其宽度和高度完全适应内容区域*/
}
```
- background-origin 设置背景相对什么位置定位

``` css
.box{
background-origin:border-box;/*背景图像相对于边框盒来定位*/
background-origin:padding-box;/*背景图像相对于内边距框来定位*/
background-origin:content-box;/*背景图像相对于内容框来定位*/
}
```
- background-clip 规定背景的绘制区域

``` css
.box{
background-clip:border-box;/*背景被裁剪到边框盒*/
/*其他值和background-origin相同*/
}
```

**Internet Explorer 9+、Firefox、Chrome、Safari 以及 Opera 支持新的背景属性。**
- css背景综合简写

``` css
.box{
background:pink url(...) no-repeat center/contain border-box padding-box;
}
```

赋值的属性依次为：背景颜色（background-color），背景图片（background-image），是否平铺（background-repeat），图片位置（background-position）/图片尺寸（background-size），background-origin，background-clip
最后三个为css3新增属性
