### ISSUE TITLE
CSS3新增功能整理七__背景渐变

### ISSUE THREAD

**Issue by EdisonZhang0401** [EdisonZhang0401/blog#8]
### CSS3背景渐变
- 线性渐变

``` css
.box{
width:200px;
height:100px;
background:linear-gradient(to left top,red,yellow);/*从左上方向开始渐变，从红变黄*/
/*方向有left、right、top、bottom、left top、left bottom、right top、right bottom*/
background:linear-gradient(60deg,red,yellow);/*从顺时针60度开始渐变*/
/*角度方向渐变，顺时针开始计算，数字代表角度，单位是deg(degree的简写)*/
}
```

**颜色可用所有颜色表达方式，可用多颜色渐变，颜色中用逗号分隔**
- 径向渐变

``` css
.box{
width:200px;
height:100px;
background:radial-gradient(aqua,blue);/*默认模式，从中心开始渐变，效果为圆形或椭圆*/
background:radial-gradient(circle,aqua,blue);/*指定渐变形状为圆，默认为ellipse(椭圆)*/
background:radial-gradient(20px,aqua,blue);/*指定渐变大小为20px*/
background:radial-gradient(80% 20%,aqua,blue);/*指定渐变大小宽高分别为80%和20%*/
background:radial-gradient(at left top,aqua,blue);/*指定渐变开始位置为左上*/
/*开始位置：center(默认)、left、right、top、bottom*/
/*left top、left bottom、right top、right bottom*/
}
```

径向渐变简写方式：background:radial-gradient(形状 大小 at 位置，颜色1，颜色2，...)
